Fix title patterns to no longer use unsupported proc
Currently the title patterns with proc prevent `puppet generate types` from working:

Error: /etc/puppetlabs/code/environments/production/modules/openldap/lib/puppet/type/openldap_access.rb: title patterns that use procs are not supported.
Error: /etc/puppetlabs/code/environments/production/modules/openldap/lib/puppet/type/openldap_dbindex.rb: title patterns that use procs are not supported.
Error: /etc/puppetlabs/code/environments/production/modules/openldap/lib/puppet/type/openldap_overlay.rb: title patterns that use procs are not supported.

https://tickets.puppetlabs.com/browse/MODULES-4505?focusedCommentId=418416&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-418416
https://github.com/treydock/puppet-module-keycloak/pull/21